### ISSUE TITLE
EventEmitter.prototype.manipulateListeners question

### ISSUE THREAD

**Issue by dhruvio** [Wolfy87/EventEmitter#86]
Hi, thanks for creating this package, I appreciate it and use it in my projects :-)

On lines [297 to 300](https://github.com/Wolfy87/EventEmitter/blob/master/EventEmitter.js#L296), I noticed you loop over the listeners to call the `single` function on each listener. Wouldn't it make more sense to just do the following since it is assumed `listeners` is an array?

    multiple.call(this, evt, listeners)

Thanks for your contribution to the community,
DD

**Comment by Wolfy87** [comment]
I can't actually see why not, thanks for taking the time to notice! I'll look into changing this. Easy way to check if it's okay though, change it and check if the tests still pass :)

If you wanted to do it yourself then that's fine too, but I'll get this added as soon as I can if not.

Thank *you* for the contribution.

**Comment by dhruvio** [comment]
Aha, so I tried running the tests locally on my side, and got a max call stack size exceeded error. The reason being the `multiple` method calls manipulateListeners, hence using `multiple` is infinitely recursive. My bad, I should've realised this!
