### ISSUE TITLE
For-in

### ISSUE THREAD

**Issue by coderaiser** [Wolfy87/EventEmitter#89]
Why don't you use `Object.keys + for` instead of `for-in`? It works [much faster](http://jsperf.com/object-keys-vs-for-in-with-closure/3), cleaner and no need to call `hasOwnProperty` all the time.

**Comment by Wolfy87** [comment]
I could do, but it means [dropping IE8 and below](http://kangax.github.io/compat-table/es5/#Object.keys). Something which would probably make a lot of people fairly unhappy. I suppose I could sniff for `typeof Object.keys === 'function'` and use alternate methods, but it could easily make the code a bit messier.

**Comment by coderaiser** [comment]
Polyfill] of [Object.keys](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys) could be used when there is no such function. So in modern browsers code would work much faster and old browsers would not be dropped out.

**Comment by Wolfy87** [comment]
Good point, that'd be the best approach. Then the only concern is extra
file size for those that just wanted a small-ish event class. Shouldn't be
too bad though, I may drop it in soon.

**Comment by desandro** [comment]
Not a bad idea, but this is an unnecessary micro-optimization IMO. Adding 40 line polyfill to improve 2 lines isn't worth it.

**Comment by nathggns** [comment]
I say leave it as it is. It's not like this is too slow.

**Comment by Wolfy87** [comment]
Thanks for the input you two. I think I'd rather keep it simple and not introduce whatever monster this is trying to prevent.

```javascript
hasDontEnumBug = !({ toString: null }).propertyIsEnumerable('toString'),
```

(from the polyfill)
