### ISSUE TITLE
Is it possible or feasible  to include the feature that register or trigger multi-listener at a time?

### ISSUE THREAD

**Issue by e-cloud** [Wolfy87/EventEmitter#92]
### Example: as a video player
```javascript
  var ee = new EventEmitter()
  ee.on('statechange', function fn1(...){
    //...
  });
  ee.on('start', function fn2(...){
    //...
  });
  ee.trigger('statechange start');
```

**Comment by Wolfy87** [comment]
You can pass a regular expression to `trigger` / `emitEvent`. So you can make the multiple emit as complex as you want, but your use case is easy enough.

```javascript
ee.trigger(/^statechange|start$/);
```

You could even write a function that tool a string, split it by spaces and compiled it into the regular expression format I've shown above with `new RegExp('^' + eventNames.split(' ').join('|') + '$');`. Actually, I basically wrote what you need there, just slap that in a function and you can have a little string DSL that builds multi-emit expressions.

**Comment by e-cloud** [comment]
As you metioned, when i scrolled to the end of the guide, i found that usage. please forgive  my thoughtlessness:sweat:

**Comment by Wolfy87** [comment]
Hah, not a problem. I hadn't thought to write a function to turn a string into a CSS selector style emit until now because of it. Good luck with whatever you're building!
